### ISSUE TITLE
    noobj_mask[b[i], anchor_ious > ignore_thres, gj[i], gi[i]] = 0 # i is index RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Shunli-Wang** [ujsyehao/yolov3-multigpu#4]
there still exist this error?
    noobj_mask[b[i], anchor_ious > ignore_thres, gj[i], gi[i]] = 0 # i is index
RuntimeError: CUDA error: device-side assert triggered

**Comment by yifan123** [comment]
I also meet this problem. hi, friend! Have you solved this?

**Comment by xungeer29** [comment]
+1
Has anyone solve it?

**Comment by WuZifan** [comment]
any help? same error!

**Comment by WuZifan** [comment]
> any help? same error!

https://github.com/zhangyongshun/Training_YOLOv3_with_Multi-GPUs

**Comment by ujsyehao** [comment]
@yifan123 @xungeer29 @WuZifan I update readme, you can refer to it 
**modify imgs_per_gpu according to your own setting**
