### ISSUE TITLE
Did anyone successfully reproduce the result from scratch？

### ISSUE THREAD

**Issue by gaopinghai** [ujsyehao/yolov3-multigpu#6]
Did anyone successfully reproduce the result from scratch？If anyone does，please provide some training details，thanks！

**Comment by ujsyehao** [comment]
I don't reproduce it.

**Comment by stevenXS** [comment]
@ujsyehao Hi, did you reproduce the result from scratch at present?

**Comment by ujsyehao** [comment]
@stevenalexis No, sorry!
