### ISSUE TITLE
why is it needed to get the batch index in build_targets

### ISSUE THREAD

**Issue by mailvijayasingh** [ujsyehao/yolov3-multigpu#8]
I wanted to understand the build_targets function in utils.py
What is the need for recalculating batch index for multi gpu training?

**Comment by ujsyehao** [comment]
我也有点记不清了,简单叙述下

- pytorch多卡训练后数据格式为[N, C, H, W]，其中N为imgs_per_gpu * num_of_gpus, data好处理，但是labels如何处理? **pytorch默认实现是对imgs, labels进行均分(即DataParallel函数)**，这样就有问题，比如有的图片实例多，有的图片实例少，直接进行均分会造成img和target不匹配，因此参考了(https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/181)找到1个batch内拥有最多实例的图片，记录最大实例数量为max_targets, 然后将这个batch内其他图片标签都扩充到这个尺寸(使用0来填充) -> 就保证了img和target是匹配上的, 此时targets变为sum_batch_size x max_targets
- 在对原始label进行处理时，首先去掉这些填充的label(0), **此处介绍下pytorch多卡计算的原理，将input平均划分到每个GPU上，再将模型复制到每个GPU上，并行地在每个GPU上做forward, 输入格式都是[N, C, H, W], 将输出值聚集到一起，传送到output_device,默认是第一个GPU, 这也是多卡训练时为何第一张显卡占用显存大的原因**
- "为何要对batch index进行重新计算?"  -> 第一步中N是sum_batch_size，对应的标签也是对应sum_batch_size, 比如imgs_per_gpu=2, num_of_gpus=2, 则label index是{0, 0, 0, 1, 1, 2, 2, 2, 3}(没有考虑第二步中对label进行扩充), 将input平均划分到每个GPU后，imgs格式[N, C, H, W]中N即为2, 为{0, 1}, 此时对于第二个GPU, 它的label index是{2, 3}和imgs index不匹配了，会造成溢出
- 最后计算多卡loss, 单卡loss = loss_sum_batch / batchsize, 多卡loss = (单卡loss1 + 单卡loss2 + ... + 单卡lossN) / GPUS
